pipeline {
  agent any
    //docker { image 'node:12-alpine' }
    
  
  stages {
    stage('Build-img') {
      steps {
        sh 'ls -l'
        sh 'pwd'
        sh 'cd app && docker build -t tbancila/tali-app:latest .'
      }
    }
    stage('Push-img') {
      steps {
        sh 'docker push tbancila/tali-app:latest'
      }
    }
  }
}
