pipeline {
  agent any
    //docker { image 'node:12-alpine' }
    
  
  stages {
    stage('Build-img') {
      steps {
        sh 'ls -l'
        sh 'pwd'
        sh 'cd app && docker build -t tbancila/tali-app:latest .'
      }
    }
    stage('Push-img') {
      steps {
        withCredentials([usernameColonPassword(credentialsId: 'docker-pwd', variable: 'password')]) {
          sh 'docker login -u "tbancila" -p "$password" docker.io'
        }
        sh 'docker push tbancila/tali-app:latest'
      }
    }
  }
}
